version: '3.1'
services:
  ecommerce-back:
    image: ecommerce-back
    container_name: ecommerce-back
    restart: always
    build: 
      context: ./
    ports:  
    - "8080:8080"
    depends_on:
      - ecommerce-db
    networks:
    - network_ecommerce

  ecommerce-db:
    image: mysql:8.0
    container_name: ecommerce-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:  
    - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Manchas12345.
    networks:
    - network_ecommerce
    
networks:
  network_ecommerce:
     external: true