spring:
  datasource:
    url: jdbc:mysql://ecommerce-db:3306/ecommerce_db?createDatabaseIfNotExist=true
    username: root
    password: Manchas12345.
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
