spring:
  datasource:
    url: jdbc:mysql://localhost:3308/ecommerce_db
    username: root
    password: Manchas12345.
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
